import type { CurrencyPeg } from "../types";

// Pure, zero-dependency reference data — same client-safe convention as
// top-traded-pairs.ts. Every rate here is a real, currently-in-force,
// publicly-documented peg (verified live this session), not an estimate.
//
// liveDataAvailable was confirmed by direct testing against this app's only
// forex data source (OANDA's practice API, via /api/chart-bars): USD/HKD and
// EUR/DKK both return real candle data consistent with their documented
// bands. USD/AED, USD/QAR, USD/BHD, USD/OMR, USD/JOD, and EUR/XOF all
// returned "Invalid value specified for 'instrument'" — OANDA doesn't quote
// them. USD/SAR is a recognized OANDA instrument but returned zero candles
// (no real liquidity behind it) — treated as unavailable for the same
// reason. These are still real, correctly-documented pegs; this app just has
// no live spot-price feed for them, and says so rather than faking one.
export const CURRENCY_PEGS: CurrencyPeg[] = [
  {
    pair: "USD/HKD",
    peggedCurrency: "HKD",
    baseCurrency: "USD",
    pegType: "band",
    targetRate: 7.8,
    bandLowerBound: 7.75,
    bandUpperBound: 7.85,
    regimeName: "Linked Exchange Rate System (LERS)",
    authority: "Hong Kong Monetary Authority",
    since: "1983 (current 7.75-7.85 band set 2005)",
    note: "The HKMA is obligated to intervene (buying or selling HKD) whenever the rate reaches either edge of the band.",
    liveDataAvailable: true,
  },
  {
    pair: "EUR/DKK",
    peggedCurrency: "DKK",
    baseCurrency: "EUR",
    pegType: "band",
    targetRate: 7.46038,
    bandLowerBound: 7.29252,
    bandUpperBound: 7.62824,
    regimeName: "ERM II fixed exchange rate policy",
    authority: "Danmarks Nationalbank",
    since: "1999",
    note: "Official ERM II tolerance band is ±2.25%; in practice Danmarks Nationalbank has kept the krone within a much tighter ±0.5% of the central rate.",
    liveDataAvailable: true,
  },
  {
    pair: "USD/AED",
    peggedCurrency: "AED",
    baseCurrency: "USD",
    pegType: "hard-fixed",
    targetRate: 3.6725,
    bandLowerBound: null,
    bandUpperBound: null,
    regimeName: "US dollar peg",
    authority: "Central Bank of the UAE",
    since: "1997",
    note: "No official trading band published; the rate is defended directly at the fixed level.",
    liveDataAvailable: false,
  },
  {
    pair: "USD/SAR",
    peggedCurrency: "SAR",
    baseCurrency: "USD",
    pegType: "hard-fixed",
    targetRate: 3.75,
    bandLowerBound: null,
    bandUpperBound: null,
    regimeName: "US dollar peg",
    authority: "Saudi Central Bank (SAMA)",
    since: "1986",
    note: "OANDA lists this instrument but returns no live candle data behind it — no real spot feed available through this app.",
    liveDataAvailable: false,
  },
  {
    pair: "USD/QAR",
    peggedCurrency: "QAR",
    baseCurrency: "USD",
    pegType: "hard-fixed",
    targetRate: 3.64,
    bandLowerBound: null,
    bandUpperBound: null,
    regimeName: "US dollar peg",
    authority: "Qatar Central Bank",
    since: "2001",
    note: "No official trading band published.",
    liveDataAvailable: false,
  },
  {
    pair: "USD/BHD",
    peggedCurrency: "BHD",
    baseCurrency: "USD",
    pegType: "hard-fixed",
    targetRate: 0.377,
    bandLowerBound: null,
    bandUpperBound: null,
    regimeName: "US dollar peg",
    authority: "Central Bank of Bahrain",
    since: "1980",
    note: "Conventionally quoted as 1 BHD = 2.6526 USD; the figure here is the inverse (BHD per 1 USD) to match this app's USD-base quoting convention.",
    liveDataAvailable: false,
  },
  {
    pair: "USD/OMR",
    peggedCurrency: "OMR",
    baseCurrency: "USD",
    pegType: "hard-fixed",
    targetRate: 0.3845,
    bandLowerBound: null,
    bandUpperBound: null,
    regimeName: "US dollar peg",
    authority: "Central Bank of Oman",
    since: "1986",
    note: "Conventionally quoted as 1 OMR = 2.6008 USD; the figure here is the inverse (OMR per 1 USD) to match this app's USD-base quoting convention.",
    liveDataAvailable: false,
  },
  {
    pair: "USD/JOD",
    peggedCurrency: "JOD",
    baseCurrency: "USD",
    pegType: "hard-fixed",
    targetRate: 0.709,
    bandLowerBound: null,
    bandUpperBound: null,
    regimeName: "US dollar peg",
    authority: "Central Bank of Jordan",
    since: "1995",
    note: "No official trading band published.",
    liveDataAvailable: false,
  },
  {
    pair: "EUR/XOF",
    peggedCurrency: "XOF",
    baseCurrency: "EUR",
    pegType: "hard-fixed",
    targetRate: 655.957,
    bandLowerBound: null,
    bandUpperBound: null,
    regimeName: "West African CFA franc peg",
    authority: "BCEAO, guaranteed by the French Treasury",
    since: "1999 (fixed rate unchanged since the 1994 CFA devaluation, re-expressed in EUR at euro launch)",
    note: "Held without devaluation since 1999.",
    liveDataAvailable: false,
  },
  {
    pair: "EUR/XAF",
    peggedCurrency: "XAF",
    baseCurrency: "EUR",
    pegType: "hard-fixed",
    targetRate: 655.957,
    bandLowerBound: null,
    bandUpperBound: null,
    regimeName: "Central African CFA franc peg",
    authority: "BEAC, guaranteed by the French Treasury",
    since: "1999 (fixed rate unchanged since the 1994 CFA devaluation, re-expressed in EUR at euro launch)",
    note: "Held without devaluation since 1999. XOF and XAF share the same EUR rate but are separate, non-interchangeable currencies.",
    liveDataAvailable: false,
  },
];

export function getCurrencyPeg(pair: string): CurrencyPeg | undefined {
  return CURRENCY_PEGS.find((p) => p.pair === pair.toUpperCase());
}
